language: python
sudo: false
dist: xenial
python:
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
install:
- pip install codecov
- pip install coverage
- pip install .
- pip install -r requirements.txt
script:
- coverage run -m unittest discover -s tests/unit && codecov -F 'unit'
- if [[ "$API_KEY" != "" ]]; then coverage run -m unittest discover -s tests/integration; fi && codecov -F 'integration'
deploy:
  provider: pypi
  user: EJEP
  skip_cleanup: true
  password: "$PYPI_PASSWORD"
  on:
    tags: true
    all_branches: true
    repo: EJEP/datapoint-python
    python: '3.8'
