language: python
sudo: false
dist: xenial
python:
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
install:
- pip install codecov
- pip install coverage
- pip install .
- pip install -r requirements.txt
script:
- nosetests -w tests/unit --with-coverage
- if [[ "$API_KEY" != "" ]]; then nosetests -w tests/integration; fi
after_success:
  - codecov
deploy:
  provider: pypi
  user: EJEP
  skip_cleanup: true
  password: "$PYPI_PASSWORD"
  on:
    tags: true
    all_branches: true
    repo: EJEP/datapoint-python
    python: '3.8'
