language: python
sudo: false
dist: xenial
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
install:
- pip install .
- pip install -r requirements.txt
script:
- nosetests -w tests/unit
- if [[ "$API_KEY" != "" ]]; then nosetests -w tests/integration; fi
deploy:
  provider: pypi
  user: jacob.tomlinson
  skip_cleanup: true
  password: "$PYPI_PASSWORD"
  on:
    tags: true
    all_branches: true
    repo: ejep/datapoint-python
    python: '3.5'
