language: python
sudo: false
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
env:
- secure: PEOM40L5TK78GFQyt2I2PgOFf8QYGcP0YZmgMhacuKnCI0Lr3wztXucWtxeVpXeuDDe12d349FumQrg6ard8T69ZZYe25eJ5lR9ZMyVOzFJ9Ew3XhoEgWBgKFRNjEkhFU+/reYWRBkYHyFImLe9d8wq1I2UMQ6z2189PLKfBtIg=
install:
- pip install .
- pip install -r requirements.txt
script:
- nosetests -w tests/unit
- if [[ "$API_KEY" != "" ]]; then nosetests -w tests/integration; fi
deploy:
  provider: pypi
  user: jacob.tomlinson
  skip_cleanup: true
  password: "$PYPI_PASSWORD"
  on:
    tags: true
    all_branches: true
    repo: jacobtomlinson/datapoint-python
    python: '3.5'
