language: python
sudo: false
dist: xenial
python: '3.7'
matrix:
  -include:
    - python: '2.6'
      dist: trusty
    - python: '2.7'
      dist: trusty
    - python: '3.3'
      dist: trusty
    - python: '3.4'
      dist: trusty
    - python: '3.5'
      dist: trusty
    - python: '3.6'
      dist: trusty
    - python: '3.7'
      dist: xenial

env:
- secure: PEOM40L5TK78GFQyt2I2PgOFf8QYGcP0YZmgMhacuKnCI0Lr3wztXucWtxeVpXeuDDe12d349FumQrg6ard8T69ZZYe25eJ5lR9ZMyVOzFJ9Ew3XhoEgWBgKFRNjEkhFU+/reYWRBkYHyFImLe9d8wq1I2UMQ6z2189PLKfBtIg=
install:
- pip install .
- pip install -r requirements.txt
script:
- nosetests -w tests/unit
- if [[ "$API_KEY" != "" ]]; then nosetests -w tests/integration; fi
deploy:
  provider: pypi
  user: jacob.tomlinson
  skip_cleanup: true
  password: "$PYPI_PASSWORD"
  on:
    tags: true
    all_branches: true
    repo: jacobtomlinson/datapoint-python
    python: '3.5'
