site_name: DataPoint for Python
theme: spacelab
nav:
- ['index.md', 'Main']
- ['README.md', 'About']
- ['install.md', 'Installation']
- ['getting-started.md', 'Getting Started']
- ['objects.md', 'Objects']
